---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.5
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    master:
      resources:
        requests:
          cpu: 21m
          memory: 150Mi
        limits:
          memory: 150Mi

    worker:
      resources:
        requests:
          cpu: 5m
          memory: 150Mi
        limits:
          memory: 150Mi
    gc:
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 1Gi
