---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: nvidia-helm-values
    config:
      name: nvidia-helm-values
    runtimeClassName: "nvidia"
    gfd:
      enabled: true
    nfd:
      enabled: false
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
