---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shokoserver
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shokoserver-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_ENDPOINT_IP
      remoteRef:
        key: ProtonVPN
        property: shokoserver_vpn_endpoint_ip
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: ProtonVPN
        property: shokoserver_wireguard_public_key
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: ProtonVPN
        property: shokoserver_wireguard_private_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: ProtonVPN
        property: wireguard_addresses
