---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-secret
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        PUSHOVER_TOKEN: "{{ .sabz_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        SABNZBD__API_KEY: "{{ .api_key }}"
        SABNZBD__NZB_KEY: "{{ .nzb_key }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: pushover
    - extract:
        key: sabnzbd
