---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app comfyui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      comfyui:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            nvidia.com/gpu.present: "true"
          runtimeClassName: nvidia
        containers:
          app:
            image:
              repository: docker.io/jahanson/comfyui
              tag: v0.0.1
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 60Gi
                nvidia.com/gpu: 1 # requesting 1 GPU
    service:
      app:
        controller: comfyui
        ports:
          http:
            port: 7860
    ingress:
      app:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host "{{ .Release.Name }}.jahanson.tech"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      models:
        enabled: true
        existingClaim: stablediffusion-checkpoints
        globalMounts:
          - path: /data/models
      config:
        enabled: true
        existingClaim: comfyui
        globalMounts:
          - path: /data/config
      output:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /output
