---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cross-seed
  namespace: flux-system
spec:
  targetNamespace: qbittorrent
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/qbittorrent/cross-seed/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
