---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  CLUSTER_SECRETS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.env"
  CLUSTER_SETTINGS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-settings.env"
  K8S_CLUSTER: '{{.K8S_CLUSTER | default "theshire"}}'
  K8S_CLUSTER_DIR: '{{.KUBERNETES_DIR}}'
  CLUSTER: '{{.CLUSTER | default "theshire"}}'
  CLUSTER_DIR: '{{.KUBERNETES_DIR}}'

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  K8S_AUTH_KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"

includes:
  volsync: .taskfiles/volsync
  precommit: .taskfiles/precommit
  k8s: .taskfiles/k8s
  flux: .taskfiles/flux
  talos: .taskfiles/talos

tasks:
  default:
    cmds: ["task -l"]
