---
# yaml-language-server: $schema=https://ks.hsn.dev/apps.emqx.io/emqx_v2beta1.json
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.1
  config:
    mode: Merge
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 3
      envFrom:
        - secretRef:
            name: emqx-secret
      extraVolumeMounts:
        - name: init-user
          mountPath: /opt/init-user.json
          subPath: init-user.json
          readOnly: true
        - name: acl-conf
          mountPath: /opt/acl.conf
          subPath: acl.conf
          readOnly: true
      extraVolumes:
        - name: init-user
          secret:
            secretName: emqx-init-user-secret
        - name: acl-conf
          configMap:
            name: emqx-acl-conf
  listenersServiceTemplate:
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: 10.1.1.38
    spec:
      type: LoadBalancer
