---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: k8s-operator-oauth-secret
    template:
      engineVersion: v2
      data:
        OAUTH_CLIENT_ID: "{{ .k8s-theshire-oauth-clientid }}"
        OAUTH_CLIENT_SECRET: "{{ .k8s-theshire-oauth-clientsecret }}"
  dataFrom:
    - extract:
        key: tailscale
