---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.78.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: k8s-operator-oauth-secret
      valuesKey: OAUTH_CLIENT_ID
      targetPath: oauth.clientId
    - kind: Secret
      name: k8s-operator-oauth-secret
      valuesKey: OAUTH_CLIENT_SECRET
      targetPath: oauth.clientSecret
  values:
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator-theshire"
      hostname: theshire
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    proxyConfig:
      defaultTags: "tag:k8s-theshire"
    apiServerProxyConfig:
      mode: "true"
