---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: autobrr-db-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: "{{ .dbname }}"
        AUTOBRR__POSTGRES_HOST: "{{ index . \"pgbouncer-host\" }}"
        AUTOBRR__POSTGRES_USER: "{{ .user }}"
        AUTOBRR__POSTGRES_PASS: "{{ .password }}"
        AUTOBRR__POSTGRES_PORT: "{{ .port }}"
  dataFrom:
    - extract:
        key: postgres-pguser-autobrr
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autobrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: autobrr
