apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: descheduler-pdb-reader
rules:
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-pdb-reader
subjects:
- kind: ServiceAccount
  name: descheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: descheduler-pdb-reader
  apiGroup: rbac.authorization.k8s.io
