---
# yaml-language-server: $schema=https://ks.hsn.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  interval: 5m
  type: oci
  # url: https://bjw-s.github.io/helm-charts/
  url: oci://ghcr.io/bjw-s/helm
  timeout: 3m
