---
# yaml-language-server: $schema=https://ks.hsn.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postfinance
  namespace: flux-system
spec:
  interval: 30m
  url: https://postfinance.github.io/kubelet-csr-approver
  timeout: 3m
