---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app coder
  namespace: flux-system
spec:
  targetNamespace: coder
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
    - name: crunchy-postgres-operator-cluster
  path: ./kubernetes/apps/coder/coder/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: true
  interval: 30m
  timeout: 5m
