---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app chronyd
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      chronyd:
        type: daemonset
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          tolerations:
            - key: node-role.kubernetes.io/master
              effect: NoSchedule
        containers:
          app:
            image:
              repository: docker.io/library/rockylinux
              tag: 9
            args:
              - "/bin/bash"
              - "-c"
              - "dnf install -y chrony iputils dnsutils && chronyd -n -d"
            resources:
              requests:
                cpu: 23m
                memory: 50M
            securityContext:
              privileged: true

    persistence:
      config:
        type: configMap
        name: chronyd-configmap
        globalMounts:
          - path: /etc/chrony.conf
            subPath: chrony.conf
            readOnly: true
      data:
        type: emptyDir
        globalMounts:
          - path: /var/lib/chrony
