---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .radarr_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        RADARR__AUTH__APIKEY: "{{ .api_key_anime }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: radarr
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: radarr-db-secret
    template:
      engineVersion: v2
      data:
        RADARR__POSTGRES__HOST: "{{ .pgbouncer-host }}"
        RADARR__POSTGRES__USER: "{{ .user }}"
        RADARR__POSTGRES__PASSWORD: "{{ .password }}"
        RADARR__POSTGRES__PORT: "{{ .port }}"
        RADARR__POSTGRES__MAINDB: radarr_main
  dataFrom:
    - extract:
        key: postgres-pguser-radarr-anime
