---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-webhooks
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: ./kubernetes/apps/flux-system/add-ons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-monitoring
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: ./kubernetes/apps/flux-system/add-ons/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: true
