---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matter-server-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: matter-server
        group: infrastructure
        url: ws://matter-server.default.svc.cluster.local:5580
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
