---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app matter-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 6.6.1
              pullPolicy: IfNotPresent
            env:
              TZ: "America/Chicago"
              MATTER_SERVER__INSTANCE_NAME: *app
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host matter.jahanson.tech
              MATTER_SERVER__LOG_LEVEL: debug
            resources:
              requests:
                memory: "100Mi"
              limits:
                memory: "300Mi"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: matter-server
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: *host
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal-nginx
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: *app
