---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pterodactyl
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      pterodactyl:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/pterodactyl/panel
              tag: v1.11.10@sha256:6c9d060396c0a2c273aa5573460ed51f9176016dac59608b414a3cb02b0cc30c
            env:
              CACHE_DRIVER: "redis"
              SESSION_DRIVER: "redis"
              QUEUE_DRIVER: "redis"
              APP_ENV: "production"
              APP_ENVIRONMENT_ONLY: "false"
              APP_TIMEZONE: America/Chicago
              TRUSTED_PROXIES: "*"
              TZ: America/Chicago
            envFrom:
              - secretRef:
                  name: pterodactyl-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: pterodactyl
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: external-nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: external.hsn.dev
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: &host "pt.hsn.dev"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app
      certs:
        globalMounts:
          - path: /etc/letsencrypt
      nginxconfig:
        globalMounts:
          - path: /etc/nginx/http.d
      ptlogs:
        globalMounts:
          - path: /app/storage/logs
      tmp:
        type: emptyDir
