---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/database_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: pterodactyl
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  characterSet: utf8
  collate: utf8_general_ci
---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/user_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pterodactyl
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  passwordSecretKeyRef:
    name: pterodactyl-secret
    key: DB_PASSWORD
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete

---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/grant_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant-pterodactyl
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: "pterodactyl"
  table: "*"
  username: pterodactyl
  grantOption: true
  host: "%"
