---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vault
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1m
  path: "./kubernetes/apps/security/vault/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
