---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: piped
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: piped-secret
    template:
      type: Opaque
      data:
        config.properties: |
          API_URL: https://piped-api.hsn.dev
          COMPROMISED_PASSWORD_CHECK: true
          DISABLE_REGISTRATION: true
          FEED_RETENTION: 30
          FRONTEND_URL: https://piped.hsn.dev
          HTTP_WORKERS: 4
          MATRIX_SERVER: https://element.infosec.exchange
          PORT: 8080
          PROXY_PART: https://piped-proxy.jahanson.tech
          SENTRY_DSN:
          hibernate.connection.driver_class: org.postgresql.Driver
          hibernate.connection.url: jdbc:postgresql://{{ index . "host" }}:5432/{{ index . "dbname" }}
          hibernate.connection.username: {{ index . "user" }}
          hibernate.connection.password: {{ index . "password" }}
  dataFrom:
    - extract:
        key: postgres-pguser-piped
