---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kometa-image-maid
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kometa-image-maid-secret
    creationPolicy: Owner
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: Plex
        property: token
