---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nvidia-device-plugin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: kube-system
  interval: 10m
  path: "./kubernetes/apps/kube-system/nvidia-device-plugin/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: false
