---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/backup_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: &name mariadb-backup
spec:
  mariaDbRef:
    name: mariadb
  timeZone: "America/Chicago"
  schedule:
    cron: "0 * * * *"
    suspend: false
  storage:
    s3:
      endpoint: s3.hsn.dev
      bucket: mariadb
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: AWS_SECRET_ACCESS_KEY
