---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/backup_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: &name mariadb-backup
spec:
  mariaDbRef:
    name: mariadb
  timeZone: "America/Chicago"
  schedule:
    cron: "0 * * * *"
    suspend: false
  stagingStorage:
    persistentVolumeClaim:
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 6Gi
      accessModes:
        - ReadWriteOnce
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
  storage:
    s3:
      endpoint: s3.hsn.dev
      bucket: mariadb
      prefix: full/
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: AWS_SECRET_ACCESS_KEY
---
# yaml-language-server: $schema=https://ks.hsn.dev/k8s.mariadb.com/backup_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: &name mariadb-pterodactyl-backup
  namespace: database
spec:
  mariaDbRef:
    name: mariadb
    namespace: database
  timeZone: "America/Chicago"
  schedule:
    cron: "0 * * * *"
    suspend: false
  stagingStorage:
    persistentVolumeClaim:
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 6Gi
      accessModes:
        - ReadWriteOnce
  podSecurityContext:
    runAsUser: 568
    runAsGroup: 568
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
  databases:
    - pterodactyl
  storage:
    s3:
      endpoint: s3.hsn.dev
      bucket: mariadb
      prefix: pterodactyl/
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: AWS_SECRET_ACCESS_KEY
