---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
    config:
      devices:
        - host: 10.1.1.68
          devices:
            - device: /dev/nvme0n1
              type: nvme
        - host: 10.1.1.69
          devices:
            - device: /dev/nvme0n1
              type: nvme
