---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      smartctl-exporter:
        type: daemonset
        containers:
          app:
            image:
              repository: quay.io/prometheuscommunity/smartctl-exporter
              tag: v0.12.0
            args:
              - --smartctl.path=/usr/sbin/smartctl
              - --smartctl.interval=120s
              - --web.listen-address=0.0.0.0:9633
              - --web.telemetry-path=/metrics
              - --smartctl.device-exclude=".*incus_root.*"
            securityContext:
              privileged: true
              runAsUser: 0
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 9633
                    path: /
              readiness: *probes
    service:
      app:
        controller: smartctl-exporter
        type: LoadBalancer
        ports:
          http:
            port: 9633
    persistence:
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /host/dev
            readOnly: true
