---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    # incompatible drives cause false positives for smart failures.
    nodeSelector:
      matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
            - gandalf-01
            - shadowfax-01
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
