---
# yaml-language-server: $schema=https://ks.hsn.dev/operator.victoriametrics.com/vmscrapeconfig_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: &name zfs-exporter
spec:
  staticConfigs:
    - targets:
        - "shadowfax.jahanson.tech:9134"
        - "gandalf.jahanson.tech:9134"
  path: /metrics
  relabelConfigs:
    - action: replace
      targetLabel: job
      replacement: *name
