---
# yaml-language-server: $schema=https://ks.hsn.dev/operator.victoriametrics.com/vmsingle_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria
spec:
  # Possible units character: h(ours), d(ays), w(eeks), y(ears). Min 24h.
  retentionPeriod: "6" # months if not specified
  useStrictSecurity: true
  serviceSpec:
    spec:
      type: LoadBalancer
      loadBalancerIP: 10.5.0.54
      ports:
        - name: http
          port: 8429
  extraArgs:
    dedup.minScrapeInterval: 10s
    maxLabelsPerTimeseries: "40"
    search.minStalenessInterval: 5m
    vmalert.proxyURL: http://vmalert-victoria.observability.svc:8080
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    fsGroup: 65534
  resources:
    requests:
      cpu: 5m
    limits:
      memory: 2Gi
  storage:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 10Gi
    storageClassName: openebs-hostpath
