---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: influxdb
        group: infrastructure
        url: tcp://influxdb.database.svc.cluster.local:8086
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
