---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app influxdb
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: { drop: ["ALL"] }
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 568
      runAsGroup: 568
      seccompProfile: { type: RuntimeDefault }
    env:
      - name: INFLUXD_REPORTING_DISABLED
        value: "true"
    persistence:
      storageClass: ceph-block
      size: 50Gi
    volumes:
      - name: tmp
        emptyDir: {}
    mountPoints:
      - name: tmp
        mountPath: /tmp
    service:
      port: 8086
    ingress:
      enabled: true
      className: internal-nginx
      hostname: "{{ Release.Name }}.jahanson.tech"
