---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .sonarr_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        SONARR__AUTH__APIKEY: "{{ .api_key_anime }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: sonarr
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-db
spec:
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: sonarr-db-secret
    template:
      engineVersion: v2
      data:
        SONARR__POSTGRES__HOST: "{{ index . \"pgbouncer-host\" }}"
        SONARR__POSTGRES__USER: "{{ .user }}"
        SONARR__POSTGRES__PASSWORD: "{{ .password }}"
        SONARR__POSTGRES__PORT: "{{ .port }}"
        SONARR__POSTGRES__MAINDB: "{{ .dbname }}"
  dataFrom:
    - extract:
        key: postgres-pguser-sonarr-anime
