---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex-trakt-sync
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/default/plex/trakt-sync"
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
    - name: plex
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
