---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm/volsync
      sourceRef:
        kind: GitRepository
        name: volsync
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: volsync-system
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image: &image
      repository: quay.io/backube/volsync
      tag: release-0.11
    rclone: *image
    restic: *image
    rsync: *image
    rsync-tls: *image
    syncthing: *image
